interface DeviceInstance {

  [key: string]: string;

  abi_list: string;
  adb_port: string;
  ads_display_time: string;
  airplane_mode_active: string;
  airplane_mode_active_time: string;
  android_google_ad_id: string;
  android_id: string;
  android_sound_while_tapping: string;
  app_launch_count: string;
  astc_decoding_mode: string;
  autohide_notifications: string;
  boot_duration: string;
  camera_device: string;
  cpus: string;
  custom_resolution_selected: string;
  device_carrier_code: string;
  device_country_code: string;
  device_custom_brand: string;
  device_custom_manufacturer: string;
  device_custom_model: string;
  device_profile_code: string;
  display_name: string;
  dpi: string;
  eco_mode_max_fps: string;
  enable_fps_display: string;
  enable_fullscreen_all_apps: string;
  enable_high_fps: string;
  enable_logcat_redirection: string;
  enable_notifications: string;
  enable_root_access: string;
  enable_vsync: string;
  fb_height: string;
  fb_width: string;
  first_boot: string;
  game_controls_enabled: string;
  gl_win_height: string;
  gl_win_screen: string;
  gl_win_x: string;
  gl_win_y: string;
  google_account_logins: string;
  google_login_popup_shown: string;
  graphics_engine: string;
  graphics_renderer: string;
  grm_ignored_rules: string;
  launch_date: string;
  libc_mem_allocator: string;
  macro_win_height: string;
  macro_win_screen: string;
  macro_win_x: string;
  macro_win_y: string;
  max_fps: string;
  pin_to_top: string;
  ram: string;
  show_sidebar: string;
  // @ts-ignore
  status: {
    adb_port: string;
    ip_addr_prefix_len: string;
    ip_gateway_addr: string;
    ip_guest_addr: string;
    session_id: string;
  };
  vulkan_supported: string;
  instance_name: string;
}